#!/bin/bash

function for_each_node {
    . /users/mmellott/w-ilab-scripts/nodes

    for i in "${nodes[@]}"; do
        echo "$i"
        ssh "$i" "$@"
    done
}

function node_map {
    . /users/mmellott/w-ilab-scripts/nodes

    for i in "${nodes[@]}"; do
        echo "$i"
        ssh "$i" "hostname && ifconfig | grep mp0 && sudo iw dev mp0 mpath dump"
        echo
    done
}

function get_ip_addr {
    local num="$(hostname | cut -d'.' -f1 | sed -e 's|[^0-9]*0*||')"
    echo "10.0.0.$num"
}

# wiphy <iface> <ip_addr>
function wiphy {
    local iface="$1"
    local ip_addr="$2"

    ifconfig "$iface" "$ip_addr"
    ifconfig "$iface" netmask 255.255.255.0
    iwconfig "$iface" txpower 1
    iwconfig "$iface" rate 6M fixed
}

# ibss <ip_addr>
function ibss {
    iwconfig wlan0 mode ad-hoc
    wiphy wlan0 "$1"
    iw dev wlan0 ibss join mellott 5180 fixed-freq aa:bb:cc:dd:ee:ff
}

# mesh <ip_addr>
function mesh {
    iw phy phy0 interface add mp0 type mp mesh_id mellott
    wiphy mp0 "$1"
}

function copy_modules {
    home=/users/fabrizio

    #netdir="net-origin"
    netdir="net-atlas"
    ath_dir="ath"
    driverdir="drivers/net/wireless/${ath_dir}/ath9k/"
    driverdir2="drivers/net/wireless/${ath_dir}/"

    #netdir="net-test"
    cp $home/atlas/kernel-3.8.0-atlas/${netdir}/wireless/cfg80211.ko /lib/modules/3.8.0-37-generic/kernel/net/wireless/
    cp $home/atlas/kernel-3.8.0-atlas/${netdir}/mac80211/mac80211.ko /lib/modules/3.8.0-37-generic/kernel/net/mac80211/
    cp $home/atlas/kernel-3.8.0-atlas/${driverdir}/*.ko /lib/modules/3.8.0-37-generic/kernel/drivers/net/wireless/ath/ath9k/
    cp $home/atlas/kernel-3.8.0-atlas/${driverdir2}/ath.ko /lib/modules/3.8.0-37-generic/kernel/drivers/net/wireless/ath/

    rmmod ath9k ath9k_common ath9k_hw ath mac80211 cfg80211
    modprobe ath9k
}

# run "iperf -D -s" on the other node
function myperf {
    iperf -c "$1" -t 200 -i 2 -yC
}

